# Default values for thredds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: unidata/thredds-docker
  tag: 4.6.20
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

persistentVolumeClaim:
  name: 'thredds-pv-claim'
  accessmodes:
    - ReadWriteOnce

service:
  type: ClusterIP
  port: 80

env:
  - name: TDM_PW
    value: 'tdm_pass'
  - name: TDS_HOST
    value: 'http://localhost'
  - name: THREDDS_XMX_SIZE
    value: '4G'
  - name: THREDDS_XMS_SIZE
    value: '4G'
  - name: TDM_XMX_SIZE
    value: '6G'
  - name: TDM_XMS_SIZE
    value: '1G'

# Data to be used for the public folder and also for the wms palettes
data:
  init_default_config: false
  # an example of a data archive is the following https://example.com/some/web/thredds_data.tgz
  public:
    init_data: false
    data_archive: ''
    subpath: 'data'
  wms_palettes:
    # an example of a wmsPalettes archive is the following https://example.com/some/web/wmsPalettes.tgz
    init_data: false
    data_archive: ''
    subpath: 'wmsPalettes'

# Configuration files: catalog.xml, threddsCatalog.xml, wmsConfig.xml, tomcat-users.xml
config_files:
  init_default_config: false
  catalog:
    init_file: false
    file_content: ''
  thredds_config:
    init_file: false
    file_content: ''
  wms_config:
    init_file: false
    file_content: ''
  tomcat_users:
    init_file: false
    file_content: ''

storage_size: 5Gi

storageClass:
  storageClassName: ''

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - /thredds

  tls: []

resources:
  requests:
    memory: '5Gi'
    cpu: '8'
  limits:
    memory: '9Gi'
nodeSelector: {}
tolerations: []
affinity: {}
