# Default values for thredds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: unidata/thredds-docker
  tag: 4.6.20-SNAPSHOT
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

persistentVolumeClaim:
  name: 'thredds-pv-claim'

service:
  type: ClusterIP
  port: 80

env:
  - name: TDM_PW
    value: 'tdm_pass'
  - name: TDS_HOST
    value: 'http://localhost'
  - name: THREDDS_XMX_SIZE
    value: '4G'
  - name: THREDDS_XMS_SIZE
    value: '4G'
  - name: TDM_XMX_SIZE
    value: '6G'
  - name: TDM_XMS_SIZE
    value: '1G'

init_default_config: false

# an example of a data archive is the following https://example.com/some/web/thredds_data.tgz
init_thredds_data: false
thredds_data_archive: ''

# an example of a catalog archive is the following https://example.com/some/web/catalog.tgz
init_catalog_xml: false
catalog_xml_archive: ''

# an example of a thredds_catalog archive is the following https://example.com/some/web/thredds_catalog.tgz
init_thredds_catalog_xml: false
catalog_thredds_xml_archive: ''

# an example of a wmsPalettes archive is the following https://example.com/some/web/wmsPalettes.tgz
init_wms_palettes: false
wms_palettes_archive: ''

# an example of a wms_config archive is the following https://example.com/some/web/wms_config.tgz
init_wms_comfig_xml: false
wms_comfig_xml_archive: ''

# an example of a tomcat-users archive is the following https://example.com/some/web/tomcat_users.tgz
init_tomcat_users: false
tomcat_users_archive: ''

storage_size: 5Gi

storageClass:
  storageClassName: ''

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - /thredds

  tls: []

resources:
  requests:
    memory: '5Gi'
    cpu: '8'
  limits:
    memory: '9Gi'
nodeSelector: {}
tolerations: []
affinity: {}
