apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-pv-claim
  labels:
{{ include "geoserver.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClass.storageClassName }}
  storageClassName: {{ .Values.storageClass.storageClassName | quote }}
  {{- end }}     
  resources:
    requests:
      storage: {{ .Values.storage_size | quote }}
