# Default values for postgis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

init_data:
  enabled: false
  repository: docker.aquaveo.com/tethys/citywater/citywater-init-containers/init_db
  tag: stable
  target_host: citywater-db.aquaveo.local
  target_user: root
  target_key: |
      "-----BEGIN RSA PRIVATE KEY-----
      MGICAQACEQDCX/y0ExwaYLjNoCGjL26lAgMBAAECEEHhkOBkHcFecMvOSkf0MsEC
       CQD8FZiJIcF2NQIJAMVk6XUZQGSxAgkA+pWRIsg+Yv0CCACtfQOy536xAggYfzyB
      LPlRVA==
      -----END RSA PRIVATE KEY-----"
  target_path: /db/archive

image:
  repository: mdillon/postgis
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: 
  - name: gitlab-registry

nameOverride: ""
fullnameOverride: ""
storage_size: 5Gi

extra_config:
  max_connections: "500"
  shared_buffers: "512MB"
  work_mem: "5MB"
  autovacuum: "on"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 2
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
