apiVersion: v2
name: djangocms
description: django-cms helm chart for the django-cms
icon: https://docs.django-cms.org/en/latest/_images/django-cms-logo.png
type: application
version: 0.1.0
appVersion: '1.16.0'
dependencies:
  - name: 'postgis'
    repository: file://../postgis
    version: '*'
    condition: postgis.enabled
