apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-pv-claim
  labels:
    app.kubernetes.io/name: {{ include "postgis.name" . }}
    helm.sh/chart: {{ include "postgis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage_size | quote }}
