# Default values for geoserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tethysplatform/geoserver
  tag: 2.8.2-2022.01.11
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

service:
  # name: geoserver
  type: ClusterIP

env:
  - name: ENABLED_NODES
    value: '4'
  - name: REST_NODES
    value: '1'
  - name: MAX_MEMORY
    value: '1024'
  - name: MIN_MEMORY
    value: '512'
  - name: NUM_CORES
    value: '8'
  - name: MAX_TIMEOUT
    value: '60'

proxy_base_url: 'http://localhost/geoserver'
init_default_config: false
default_config_archive: 'https://example.com/some/web/archive.tgz'
storage_size: 5Gi
storageClass:
  storageClassName: ''
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - /geoserver

  tls: []

resources:
  requests:
    memory: '5Gi'
    cpu: '8'
  limits:
    memory: '9Gi'
nodeSelector: {}
tolerations: []
affinity: {}
