apiVersion: v2
appVersion: '1.0'
description: 'Helm chart for GeoServer Cloud.'
icon: https://avatars.githubusercontent.com/u/186522?s=48&v=4
name: gs-cloud
version: 0.1.10
dependencies:
  - name: 'rabbitmq'
    version: '*'
    repository: 'oci://registry-1.docker.io/cloudpirates'
    condition: rabbitmq.enabled

  - name: 'postgresql'
    repository: 'oci://registry-1.docker.io/cloudpirates'
    version: '*'
    condition: postgresql.enabled

  - name: geoservercloud
    repository: https://camptocamp.github.io/helm-geoserver-cloud
    version: '*'

  - name: pgcat
    repository: "https://postgresml.github.io/pgcat"
    version: "0.2.5"
    condition: pgcat.enabled