
acl:
  enabled: false

jndi:
  enabled: false

env: &env-override
  SPRING_PROFILES_ACTIVE:
    value: standalone,datadir
  JAVA_OPTS:
    value: '$(JAVA_OPTS_DEFAULT) -XshowSettings:system'
    order: 1
  JAVA_OPTS_DEFAULT:
    value: '-DALLOW_ENV_PARAMETRIZATION=true -XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=80'
  GEOWEBCACHE_CACHE_DIR:
    value: '/mnt/cache'

additional-stuff: &additional-stuff
  containers:
    spring:
      env:
        <<: *env-override


service: &common-service-definition
  type: ClusterIP
  servicePort: 8080
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http

geoservercloud:
  global:
    profile: standalone,datadir
  geoserver:
    ingress:
      annotations: {}
      enabled: true
      hostGroups:
        host1:
          tls:
            enabled: false
          hosts:
            - localhost
    services:
      gateway:
        <<: *additional-stuff
        service:
          annotations: {}
          labels: {}
          <<: *common-service-definition
        ingress:
          enabled: true
      webui:
        <<: *additional-stuff
        service:
          <<: *common-service-definition

      rest:
        <<: *additional-stuff
        service:
          <<: *common-service-definition

      wms:
        replicaCount: 1
        <<: *additional-stuff
        service:
          <<: *common-service-definition

      wcs:
        <<: *additional-stuff
        service:
          <<: *common-service-definition

      wfs:
        replicaCount: 1
        <<: *additional-stuff
        service:
          <<: *common-service-definition

      gwc:
        replicaCount: 1
        <<: *additional-stuff
        service:
          <<: *common-service-definition

pgcat:
  enabled: false