apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "geoserver.fullname" .) }}
  labels:
{{ include "geoserver.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: main-node
      port: 8181
      targetPort: 8181
    - name: node-1
      port: 8081
      targetPort: 8081
    - name: node-2
      port: 8082
      targetPort: 8082
    - name: node-3
      port: 8083
      targetPort: 8083
    - name: node-4
      port: 8084
      targetPort: 8084

  selector:
    app.kubernetes.io/name: {{ include "geoserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
