{{- if and .Values.dataDirectory.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-pv-claim
  labels:
    {{- include "geoserver-official.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.dataDirectory.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.dataDirectory.persistence.size }}
  {{- if .Values.dataDirectory.persistence.storageClass }}
  storageClassName: {{ .Values.dataDirectory.persistence.storageClass }}
  {{- end }}
{{- end }}
