apiVersion: v1
data:
  01_init_db.sql: |+
    CREATE DATABASE {{ .Values.configMaps.postgresql_init.database }};
    CREATE ROLE {{ .Values.configMaps.postgresql_init.username }} WITH LOGIN PASSWORD '{{ .Values.configMaps.postgresql_init.password }}';
    ALTER DATABASE {{ .Values.configMaps.postgresql_init.database }} OWNER TO {{ .Values.configMaps.postgresql_init.username }} ;
    \c {{ .Values.configMaps.postgresql_init.database }}
    CREATE EXTENSION postgis;
    CREATE SCHEMA data;
    CREATE SCHEMA config;
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.configMaps.postgresql_init.name }}
