apiVersion: v1
kind: PersistentVolume
metadata:
  name: gs-cloud-gwc-cache-nfs-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/gwccache"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gs-cloud-gwc-cache-nfs-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
