apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "thredds.fullname" .) }}
  labels: 
{{ include "thredds.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
  {{- end }}

  selector:
    app.kubernetes.io/name: {{ include "thredds.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
