apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thredds.fullname" . }}
  labels:
{{ include "thredds.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thredds.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "thredds.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.init_default_config }}
      initContainers:
      {{- if .Values.init_tomcat_users -}}
        - name: init-tomcat-users-xml
          image: alpine:3.10.0
          command: ['sh', '-c', '[ "$(ls -A /thredds/tomcat-users.xml)" ] && (echo "tomcat-users.xml is already there"; true) || (echo "Setting up tomcat-users.xml"; cd /thredds; wget {{ .Values.tomcat_users_archive }} -O - | base64 -d | tar xzf - --strip-components=1)']
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/thredds'
              subPath: tomcat-users.xml
      {{- end -}}
      {{- if .Values.init_catalog_xml -}}
        - name: init-catalog-xml
          image: alpine:3.10.0
          command: ['sh', '-c', '[ "$(ls -A /thredds/catalog.xml)" ] && (echo "catalog.xml is already there"; true) || (echo "Setting up catalog.xml"; cd /thredds; wget {{ .Values.catalog_xml_archive }} -O - | base64 -d | tar xzf - --strip-components=1)']
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/thredds'
              subPath: catalog.xml
      {{- end -}}
      {{- if .Values.init_thredds_catalog_xml -}}
        - name: init-thredds-catalog-xml
          image: alpine:3.10.0
          command: ['sh', '-c', '[ "$(ls -A /thredds/threddsCatalog.xml)" ] && (echo "threddsCatalog.xml is already there"; true) || (echo "Setting up threddsCatalog.xml"; cd /thredds; wget {{ .Values.catalog_thredds_xml_archive }} -O - | base64 -d | tar xzf - --strip-components=1)']
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/thredds'
              subPath: threddsCatalog.xml
      {{- end -}}
      {{- if .Values.init_wms_comfig_xml -}}
        - name: init-wms-config-xml
          image: alpine:3.10.0
          command: ['sh', '-c', '[ "$(ls -A /thredds/wmsConfig.xml)" ] && (echo "wmsConfig.xml is already there"; true) || (echo "Setting up wmsConfig.xml"; cd /thredds; wget {{ .Values.wms_comfig_xml_archive }} -O - | base64 -d | tar xzf - --strip-components=1)']
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/thredds'
              subPath: wmsConfig.xml
      {{- end -}}      
      {{- if .Values.init_wms_palettes -}}
        - name: init-wms-palettes
          image: alpine:3.10.0
          command: ['sh', '-c', '[ "$(ls -A /thredds/wmsPalettes)" ] && (echo "/thredds/wmsPalettes already contains files"; true) || (echo "Setting up /thredds/wmsPalettes"; cd /thredds/wmsPalettes; wget {{ .Values.wms_palettes_archive }} -O - | base64 -d | tar xzf - --strip-components=1)']
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/thredds'
              subPath: wmsPalettes
      {{- end -}}
      {{- if .Values.init_thredds_data }}
        - name: init-myservice
          image: alpine:3.10.0
          command: ['sh', '-c', '[ "$(ls -A /thredds/data)" ] && (echo "/thredds/data already contains files"; true) || (echo "Setting up /thredds/data"; cd /thredds/data; wget {{ .Values.thredds_data_archive }} -O - | base64 -d | tar xzf - --strip-components=1)']
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/thredds'
              subPath: data
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }} 
          ports:
            - containerPort: 8080
              name: main-node
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/usr/local/tomcat/content/thredds'
              subPath: thredds
      volumes:
        - name: thredds-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
