{{- $fullName := include "thredds.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thredds.fullname" . }}
  labels:
{{ include "thredds.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thredds.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "thredds.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.init_default_config }}
      initContainers:
      {{- if .Values.data.wms_palettes.init_data -}}
        - name: init-wms-palettes
          image: alpine:3.10.0
          command: ['sh', '-c', '[ "$(ls -A /thredds)" ] && (echo "/thredds already contains files"; true) || (echo "Setting up /thredds"; cd /thredds; wget {{ .Values.data.wms_palettes.data_archive }} -O - | base64 -d | tar xzf - --strip-components=1)']
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/thredds/{{ .Values.data.wms_palettes.subpath }}'
              subPath: {{ .Values.data.wms_palettes.subpath }}
      {{- end -}}
      {{- if .Values.data.public.init_data -}}
        - name: init-public-folder
          image: alpine:3.10.0
          command: ['sh', '-c', '[ "$(ls -A /thredds)" ] && (echo "/thredds already contains files"; true) || (echo "Setting up /thredds"; cd /thredds; wget {{ .Values.data.public.data_archive }} -O - | base64 -d | tar xzf - --strip-components=1)']
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/thredds/{{ .Values.data.public.subpath }}'
              subPath: {{ .Values.data.public.subpath }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }} 
          ports:
            - containerPort: 8080
              name: main-node
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: thredds-persistent-storage
              mountPath: '/usr/local/tomcat/content/thredds'
              subPath: thredds
            {{- if .Values.data.init_default_config -}}
            {{- if .Values.data.public.init_data -}}
            - name: thredds-persistent-storage
              mountPath: '/usr/local/tomcat/content/thredds/public/{{ .Values.data.public.subpath }}'
              subPath:  {{ .Values.data.public.subpath }}
            {{- end -}}
            {{- if .Values.data.wms_palettes.init_data -}}
            - name: thredds-persistent-storage
              mountPath: '/usr/local/tomcat/content/thredds/{{ .Values.data.wms_palettes.subpath }}'
              subPath: {{ .Values.data.wms_palettes.subpath}}
            {{- end -}}
            {{- end -}}
            {{- if .Values.config_files.init_default_config -}}              
            {{- if .Values.config_files.catalog.init_file }}
            - name: config-volume
              mountPath: '/usr/local/tomcat/content/thredds/catalog.xml'
              subPath: catalog.xml
            {{- end }}
            {{- if .Values.config_files.thredds_catalog.init_file -}}
            - name: config-volume
              mountPath: '/usr/local/tomcat/content/thredds/threddsConfig.xml'
              subPath: threddsConfig.xml
            {{- end -}}
            {{- if .Values.config_files.wms_config.init_file -}}
            - name: config-volume
              mountPath: '/usr/local/tomcat/content/thredds/wmsConfig.xml'
              subPath: wmsConfig.xml
            {{- end -}}
            {{-if .Values.config_files.tomcat_users.init_file -}}
            - name: config-volume
              mountPath: '/usr/local/tomcat/content/thredds/tomcat-users.xml'
              subPath: tomcat-users.xml
            {{- end -}}
            {{- end -}}
      volumes:
        - name: thredds-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.name }}
        - name: config-volume
          configMap:
            name: "{{ $fullName }}-configmap"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
