{{- $defaultPvcName := include "thredds.pvcname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $defaultPvcName |quote }}
  labels:
{{ include "thredds.labels" . | indent 4 }}
spec:
  accessModes:
  {{- range .Values.persistentVolumeClaim.accessModes }}
    - {{ . }}
  {{- end }}
  {{- if .Values.storageClass.storageClassName }}
  storageClassName: {{ .Values.storageClass.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage_size | quote }}