{{- $fullName := include "thredds.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default "{{ $fullName }}-pvc" .Values.persistentVolumeClaim.name | quote }}
  labels:
{{ include "thredds.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClass.storageClassName }}
  storageClassName: {{ .Values.storageClass.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage_size | quote }}
