apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thredds-pv-claim
  labels:
{{ include "thredds.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage_size | quote }}
