apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "thredds.fullname" .) }}
  labels: 
{{ include "thredds.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: main-node
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "thredds.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
