{{- if (eq .Values.postgresql.enabled true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  install-postgis.sh: |
    #!/bin/bash
    set -e
    echo "Creating PostGIS extension..."
    psql -U {{ .Values.postgresql.auth.user | default "postgres" }} \
    -d {{ .Values.postgresql.auth.database | default "postgres" }} \
    -c "CREATE EXTENSION IF NOT EXISTS postgis;"
{{- if .Values.jndi.enabled }}
  create_schemas.sql: |
    \c {{ .Values.postgresql.auth.database | default "postgres" }}
    CREATE SCHEMA data;
    CREATE SCHEMA config;
{{- end }}
{{- end }}