{{- range $key, $definition := .Values.persistent }}
---
{{- if and $definition.pvcreation }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $definition.pvname }}
spec:
  accessModes:
    - {{ $definition.accessModes }}
  capacity:
    storage: {{ $definition.storage }}
  mountOptions:
    - {{ $definition.mountOptions }}
  nfs:
    path: {{ $definition.path }}
    server: {{ $definition.nfsserver }}
  persistentVolumeReclaimPolicy:
    {{ $definition.persistentVolumeReclaimPolicy }}
  storageClassName: {{$definition.storageClassName}}
  
{{- end }}

{{- end }}