# This is a basic workflow to help you get started with Actions
name: CI

# Push to docker hub if tag has been created.
on:
  push:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Helm
#        uses: igabaydulin/helm-check-action@master
#        env:
#          CHART_LOCATION: ./geoserver
#          CHART_VALUES: ./geoserver/values.yaml
        uses: WyriHaximus/github-action-helm3@v1
        with:
          exec: helm lint ./postgis/