# This is a basic workflow to help you get started with Actions
name: CI

# Push to docker hub if tag has been created.
on:
  push:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-helm-geoserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Env
        run: |
          echo ::set-env name=TAG::${GITHUB_REF:11}
          echo ::set-env name=GIT_USERNAME::${{ secrets.GIT_USERNAME }}
          echo ::set-env name=GIT_PASSWORD::${{ secrets.GIT_PASSWORD }}
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v1.0.0
        with:
          exec: helm lint ./geoserver
      - name: Package Helm
        uses: WyriHaximus/github-action-helm3@v1.0.0
        with:
          exec: helm package ./geoserver
      - name: Copy Helm Package to docs
        run: |
          cd ${{github.workspace}} &&
          LOCAL_PACKAGE=$(ls *.tgz | head -n1) &&
          echo $LOCAL_PACKAGE &&
          mv --backup=t $LOCAL_PACKAGE ./docs/$LOCAL_PACKAGE
      - name: Create new index file
        uses: WyriHaximus/github-action-helm3@v1.0.0
        with:
          exec: ls . && helm repo index ./docs --url https://aquaveo.github.io/misc-helm-charts/
      - name: Copy Helm Package to docs
        run: |
          LOCAL_PACKAGE=$(ls ./docs/*.tgz | head -n1) &&
          echo $LOCAL_PACKAGE &&
          git config --global user.name "githubactions" &&
          git config --global user.email "htran@aquaveo.com" &&
          git remote set-url origin "https://${{ env.GIT_USERNAME }}:${{ env.GIT_PASSWORD }}@github.com/${{ env.GIT_USERNAME }}/project.git" &&
          git checkout $TAG &&
          git add . &&
          git commit -m "Update Geoserver" &&
          git push &&
          git status
