# This is a basic workflow to help you get started with Actions
name: CI

# Push to docker hub if tag has been created.
on:
  push:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-helm-geoserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Tag
      run: |
        echo ::set-env name=TAG::${GITHUB_REF:10}
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v1.0.0
        with:
          exec: helm lint ./geoserver
      - name: Package Helm
        uses: WyriHaximus/github-action-helm3@v1.0.0
        with:
          exec: helm package ./geoserver
      - name: Push Helm Package to github
        run: |
          cd ${{github.workspace}} &&
          LOCAL_PACKAGE=$(ls *.tgz | head -n1) &&
          echo $LOCAL_PACKAGE &&
          git checkout $TAG &&
          git status
