name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add Helm repos for gs-cloud deps
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add camptocamp https://camptocamp.github.io/helm-geoserver-cloud
          helm repo add pgcat https://postgresml.github.io/pgcat
          helm repo update

      - name: Vendor gs-cloud dependencies (debug)
        run: |
          rm -f charts/gs-cloud/Chart.lock
          helm dependency build charts/gs-cloud -v 10
          ls -lah charts/gs-cloud/charts


      - name: Debug chart before packaging
        run: |
          set -euxo pipefail
          cat charts/gs-cloud/Chart.yaml
          test -d charts/gs-cloud/charts
          ls -lah charts/gs-cloud/charts
          helm dependency list charts/gs-cloud
          if [ -f charts/gs-cloud/.helmignore ]; then
            echo ".helmignore:"; cat charts/gs-cloud/.helmignore; fi
          helm lint charts/gs-cloud || true

      - name: Run chart-releaser for gs-cloud
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts

      - name: Run chart-releaser thredds
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts

      - name: Run chart-releaser geoserver
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts

      - name: Run chart-releaser postgis
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts

      - name: Run chart-releaser djangocms
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts

      - name: Run chart-releaser geoserver-official
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
