name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser for gs-cloud
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_dependencies: false
          charts_dir: charts/gs-cloud

      - name: Run chart-releaser thredds
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts/thredds

      - name: Run chart-releaser geoserver
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts/geoserver

      - name: Run chart-releaser postgis
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts/postgis

      - name: Run chart-releaser djangocms
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts/djangocms

      - name: Run chart-releaser geoserver-official
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: ghcr.io/aquaveo
          oci_username: aquaveo
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts/geoserver-official
