name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm lint ./geoserver && helm lint ./postgis && helm lint ./thredds && helm lint ./gs-cloud && helm lint ./gs-cloud/charts/helm-geoserver-cloud

      - name: Add Dependency repos and updating chart dependencies
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo add helm-custom-pod https://camptocamp.github.io/helm-custom-pod/ && helm dependency update ./gs-cloud/charts/helm-geoserver-cloud

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
