name: Update Helm

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'

jobs:
  update-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Env
        run: |
          echo "TAG=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm lint ./geoserver && helm lint ./postgis
      - name: Package Geoserver Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./geoserver
      - name: Package PostGIS Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./postgis
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ​${{ secrets.GITHUB_TOKEN }}
      # - name: Push Changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GIT_PASSWORD }}