name: Update Helm Packages

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  update-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Env
        run: |
          echo "TAG=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm lint ./geoserver && helm lint ./postgis && helm lint ./thredds && helm lint ./gs-cloud

      - name: Package GeoServer Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./geoserver -d ./docs

      - name: Package Thredds Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./thredds -d ./docs

      - name: Package GeoServer Cloud Parent Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./helm-geoserver-cloud -d ./docs

      - name: Package GeoServer Cloud Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./gs-cloud -d ./docs

      - name: Package PostGIS Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./postgis -d ./docs

      - name: Update Index yaml file
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm repo index ./docs
