name: Update Helm

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  update-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Env
        run: |
          echo "TAG=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm lint ./geoserver && helm lint ./postgis
      - name: Package GeoServer Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./geoserver
      - name: Package PostGIS Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./postgis
      - name: Login to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: echo "${{ github.actor }}" | helm registry login -u ${{ secrets.GITHUB_TOKEN }} ghcr.io --password-stdin
      - name: Push GeoServer Helm Package to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: |
            export CHART_VERSION=$(grep 'version:' ./geoserver/Chart.yaml | tail -n1 | awk '{ print $2}')
            helm push geoserver-${CHART_VERSION}.tgz oci://ghcr.io/aquaveo
      - name: Push PostGIS Helm Package to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: |
            export CHART_VERSION=$(grep 'version:' ./postgis/Chart.yaml | tail -n1 | awk '{ print $2}')
            helm push postgis-${CHART_VERSION}.tgz oci://ghcr.io/aquaveo
