name: Update Helm Packages

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  update-helm:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set Env
        run: |
          echo "TAG=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm lint ./geoserver && helm lint ./postgis && helm lint ./thredds && helm lint ./gs-cloud

      - name: Add Dependency repos
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo helm-custom-pod add https://camptocamp.github.io/helm-custom-pod/

      - name: Package GeoServer Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./geoserver -d ./docs

      - name: Package Thredds Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./thredds -d ./docs

      - name: Package GeoServer Cloud Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm dependency update ./gs-cloud/charts/helm-geoserver-cloud && helm dependency update ./gs-cloud && helm package ./gs-cloud -d ./docs

      - name: Package PostGIS Helm
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm package ./postgis -d ./docs

      - name: Update Index yaml file
        uses: WyriHaximus/github-action-helm3@v3.0.1
        with:
          exec: helm repo index ./docs
